### ISSUE TITLE
delay de espera ACK

### ISSUE THREAD

**Issue by fernandoeqc** [ezequieldonhauser/NRF24L01P#2]
O tempo de espera_ack ESTÁ 400, diferente do teste que é feito no  if(espera_ack==500). O tempo deveria ser o mesmo??

`while(input(IRQ)==1){
      espera_ack++;
      //espera 5ms, pela recepçao do pacote ACK
      if(espera_ack==500)
      {
               break;////////////sai do while
      }`
`if(espera_ack==500)
   {     clear_interrupt(int_ext);
         enable_interrupts(GLOBAL);
         return(0);
   }`

**Comment by ezequieldonhauser** [comment]
esse tempo é baseado na velocidade que o pic le o SPI para pegar o status, entao 400 nao representa exatamente 5ms, eu testei com o osciloscopio, apenas para ter uma referencia
